import {
  createIcons,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  BookOpen,
  CalendarCheck,
  CalendarClock,
  CalendarPlus,
  ChartArea,
  ChartNoAxesCombined,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  Clock3,
  CloudCheck,
  Compass,
  Eraser,
  Download,
  Flag,
  FlaskConical,
  Gauge,
  GraduationCap,
  HardDrive,
  History,
  Layers3,
  LayoutDashboard,
  ListChecks,
  LockKeyhole,
  Menu,
  Network,
  NotebookTabs,
  Play,
  RefreshCw,
  RotateCcw,
  SearchX,
  Send,
  Settings,
  Target,
  Timer,
  Trash2,
  Upload,
  Zap
} from 'lucide';

const icons = {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  BookOpen,
  CalendarCheck,
  CalendarClock,
  CalendarPlus,
  ChartArea,
  ChartNoAxesCombined,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  Clock3,
  CloudCheck,
  Compass,
  Eraser,
  Download,
  Flag,
  FlaskConical,
  Gauge,
  GraduationCap,
  HardDrive,
  History,
  Layers3,
  LayoutDashboard,
  ListChecks,
  LockKeyhole,
  Menu,
  Network,
  NotebookTabs,
  Play,
  RefreshCw,
  RotateCcw,
  SearchX,
  Send,
  Settings,
  Target,
  Timer,
  Trash2,
  Upload,
  Zap
};

export function icon(name, label = '') {
  return `<i data-lucide="${name}"${label ? ` aria-label="${label}"` : ' aria-hidden="true"'}></i>`;
}

export function refreshIcons(root = document) {
  createIcons({ icons, attrs: { 'stroke-width': 1.8 }, nameAttr: 'data-lucide', root });
}
